name: isolate_handler
description: Effortless isolates abstraction layer with support for inter-isolate communication.
version: 1.0.1
homepage: https://github.com/deakjahn/isolate_handler
documentation: https://github.com/deakjahn/isolate_handler/blob/0.2.0/README.md

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # flutter_isolate: ^2.0.2

  # Pending PR:
  # https://github.com/rmawatson/flutter_isolate/pull/118
  flutter_isolate:
    git:
      url: https://github.com/srmanc/flutter_isolate.git
      ref: 156fa6518d280466b8b042b8316768319dc2ccc5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
